### ISSUE TITLE
Set Z=0 to the middle of the Bed before leveling...

### ISSUE THREAD

**Issue by Dominik-1980** [Pmatsol58/VyperCE6.1#8]
### Is your feature request related to a problem? Please describe.

Not a problem, but it would look nicer and clearer in the leveling mesh...

### Describe the feature you want

If I do a bed leveling, it shows me values between -2,4 and -2,00.
It would look much better in the leveling mesh if I could set to Z=-2,2 in this case.
This is approximately the center of the bed.

The firmware could take one probe at the center of the bed and set this value to Z=0,
then do the automatic bed leveling...

**Comment by Pmatsol58** [comment]
There is a build option to use the nozzle as the Z endstop for homing and this will probe the centre of the bed when homing the Z axis, leveling will then be based around this figure giving values closer to 0. There are disadvantages to this too in that you cannot home with anything on the bed and a G34 has to be used to level the two Z screws rather than use the Z optical stops on each side of the bed.

**Comment by Dominik-1980** [comment]
Okay. Thanks for your response.

I will leave it as it is.
The disadvantages of homing with the probe prevail,
just to look nicer on the leveling...
